# Generated by Django 2.1.4 on 2018-12-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('hostname', models.CharField(blank=True, max_length=128, null=True, verbose_name='hostname')),
                ('export_path', models.TextField(blank=True, null=True, verbose_name='export path')),
                ('function_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='function name')),
            ],
        ),
    ]
