# Generated by Django 2.1.4 on 2018-12-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionJobsShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jobs_shares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='comments')),
                ('shares', models.ManyToManyField(related_name='jobs', related_query_name='jobs', through='action_jobs.ActionJobsShares', to='shares.Share', verbose_name='shares')),
            ],
        ),
    ]
